// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransportManagementSystem.Database;

#nullable disable

namespace TransportManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransportManagementSystem.Models.Chauffeur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateExpirationPermis")
                        .HasColumnType("date");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroPermis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Chauffeurs");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Horaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChauffeurId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateArrivee")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateDepart")
                        .HasColumnType("date");

                    b.Property<int>("TrajetId")
                        .HasColumnType("integer");

                    b.Property<int>("VehiculeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChauffeurId");

                    b.HasIndex("TrajetId");

                    b.HasIndex("VehiculeId");

                    b.ToTable("Horaires");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.ModePaiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ModePaiements");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DatePaiement")
                        .HasColumnType("date");

                    b.Property<int>("ModePaiementId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Montant")
                        .HasColumnType("numeric");

                    b.Property<int>("ReservationId")
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ModePaiementId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateReservation")
                        .HasColumnType("date");

                    b.Property<int>("HoraireId")
                        .HasColumnType("integer");

                    b.Property<int>("NumSiege")
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("HoraireId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Trajet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("HeureArrivee")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HeureDepart")
                        .HasColumnType("time without time zone");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric");

                    b.Property<int>("VilleArriveeId")
                        .HasColumnType("integer");

                    b.Property<int>("VilleDepartId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Trajets");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Vehicule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("annee")
                        .HasColumnType("integer");

                    b.Property<int>("capacite")
                        .HasColumnType("integer");

                    b.Property<string>("marque")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("modele")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("plaque")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vehicules");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Ville", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NomVille")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Villes");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Horaire", b =>
                {
                    b.HasOne("TransportManagementSystem.Models.Chauffeur", "Chauffeur")
                        .WithMany()
                        .HasForeignKey("ChauffeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportManagementSystem.Models.Trajet", "Trajet")
                        .WithMany()
                        .HasForeignKey("TrajetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportManagementSystem.Models.Vehicule", "Vehicule")
                        .WithMany()
                        .HasForeignKey("VehiculeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chauffeur");

                    b.Navigation("Trajet");

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Paiement", b =>
                {
                    b.HasOne("TransportManagementSystem.Models.ModePaiement", "ModePaiement")
                        .WithMany()
                        .HasForeignKey("ModePaiementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportManagementSystem.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModePaiement");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Reservation", b =>
                {
                    b.HasOne("TransportManagementSystem.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportManagementSystem.Models.Horaire", "Horaire")
                        .WithMany()
                        .HasForeignKey("HoraireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Horaire");
                });
#pragma warning restore 612, 618
        }
    }
}
